baseURL: "https://jeremymiller.me"
languageCode: "en-us"
title: "Jeremy Miller"
theme: hugo-profile

Paginate: 3
# googleAnalytics: G-

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  title: "Jeremy Miller"
  description: Text about my cool site
  favicon: "/jm_logo.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor: 
  #   secondaryTextColor: 
  #   backgroundColor: 
  #   secondaryBackgroundColor: 
  #   primaryColor: 
  #   secondaryColor: 

  #   darkmode:
  #     textColor: 
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Jeremy."
    subtitle: "I am a system engineer."
    content: "I really fight an onslaught of constantly evolving work load with the idea of automation and removal of and prevention of accrual of technical debt."
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume PDF Download"
      url: "resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jmi3/
        - icon: fab fa-github
          url: https://github.com/som3guy
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"


  # About
  about:
    enable: true
    title: "About Me"
    image: "/me.png"
    content: |-
      I am a system engineer with a passion for monitoring. I have a background in computer science, and I have a strong interest monitoring and security. I am currently working as a system engineer II at [Cerner](https://cerner.com) in Kansas City, MO. 
      
      I am currently working on a Splunk team in Cerner that monitors a large amount of the logs our company generates and provide Splunk as a SaaS.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Splunk"
        - "Zabbix"
        - "Chef"
        - "Ruby"
        - "Bash"
        - "git"

  # Experience
  experience:
    enable: true
    items:
      - job: "System Engineer II"
        company: "Oracle / Cerner"
        companyUrl: "https://oracle.com"
        date: "Aug 2014 - present"
        content: |
          I am currently working as a system engineer II at [Oracle/Cerner](https://oracle.com) remotely. I have done a lot and grown quite a bit working here on projects and team including:
          - Splunk team
            - Mitigating vulnerabilities
            - Run projects
            - Assisting senior and junior team members accomplish tasks
            - Support the numerous environments for clients internally and across the globe
          - Zabbix team
            - Determine and implement needed infrastructure
            - Determine and establish best practices
          - Ruby and bash scripting
          - Create, update, and maintain F5 loadbalancer configs and certificates
          - Writing, updating, maintaining chef cookbooks
          - Running ansible playbooks
          - Utilizing git and enterprise github
          - Automate what we can and reduce existing technical debt when I can
          - Utilize Chef to standardize deployments and keep all configuration in source control
          - Work internally with teamates as well as will other teams to complete projects or resolve issues
          - Work as a primary on call in a rotation as well as 24/7 on call for solutions I am a subject matter expert in
          - Utilze JIRA for issue tracking. 
          - Really what I do is figure out what to do even if no one has the knowledge to proceed. I figure it out and get it done. The Internet usually has all the pieces of how to get something done, I just put the puzzle together at the end of the day to deliver what is required of our team at the time.
      
      - job: "Linux Support Analyst"
        company: "A2 Hosting"
        companyUrl: "https://www.a2hosting.com/"
        date: "Feb 2014 - Jul 2014"
        content: |
          A2 Hosting web hosting company based out of Ann Arbor Michigan. They offer everything from a basic website to high-performance virtual private servers.
          - Work remotely from home.
          - Support Customers via Phone, Live Chat, and Support Tickets.
          - Migrate client cPanel accounts from other hosts to our servers as well as internally.
          - Assist customers with Pre-sales and sales questions.
          - Provide server-side support for hosting services.
          - Review abusive accounts and proceed accordingly.
          - Work with 3rd party abuse companies to take down malicious sites.
      
      - job: "Department Manager"
        company: "Technology Experts"
        companyUrl: "https://mytechexperts.com/"
        date: "Mar 2012 - Feb 2014"
        content: |
          Technology Experts is a managed service provider based out of Monroe Michigan. The provide the full IT department experience without having to hire an on-site IT staff.
          - Migrated users and all data from one PC to another.
          - Virus Removal
          - Hardware and software installation.
          - Dealt with Software manufacturers to repair, recover, or transfer their software.
          - Managed hardware and software firewalls to open or restrict access.
          - Operating system installation and maintenance (OS and NOS)
          - Technical Remote Support.
          - Create self-service documentation.
          - Outlook and Exchange issues.
          - Migrate Websites to Wordpress and manage domains and mail in Plesk.
          - Mass workstation /email migrations
  
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Computer Science in Information Security"
        school:
          name: "ITT-Technical Institute of Technology"
          url: "https://en.wikipedia.org/wiki/ITT_Technical_Institute"
        # date: 
      - title: "Associates of Computer Science in Computer Networking"
        school:
          name: "ITT-Technical Institute of Technology"
          url: "https://en.wikipedia.org/wiki/ITT_Technical_Institute"
        # date: 
      
  # Achievements
  achievements:
    enable: true
    items:
      - title: CompTIA Security + 
        content: Credential ID C68N9KNH8HQ41B3W
        url: https://www.credly.com/badges/561d7f65-9626-40f7-b092-94e86e4aa0a6/public_url
      - title: Splunk Certified Admin
        content: Credential ID Cert-338595
        url: https://www.credly.com/badges/6cd63e9b-610f-4d89-b6a0-6187f3d03566/public_url
      - title: Splunk Certified Power User
        content: Credential ID Cert-269090
        url: https://www.credly.com/badges/5adcb8cf-755e-4231-bec9-37f9b9aa3297/public_url
      - title: Splunk Certified User
        content: Credential ID Cert-269288
        url: https://www.credly.com/badges/fc22eb77-449e-45e0-b2da-358bb0c91cac/public_url
      - title: Zabbix Certified Professional
        content: Credential ID CP1510-06
        url: https://www.zabbix.com/training_professional
      - title: Chef Fluency Badge
        content: Expired 2020 - This badge showed basic proficiency with Chef
      - title:  RHCSA Certificate
        content: Expired 2019 - I had this Certificate but did not pursue keeping it active. 


  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: jmiller3346@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/som3guy
      linkedin: https://www.linkedin.com/in/jmi3/
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

